coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    # https://docs.codecov.com/docs/commit-status#patch-status
    patch:
      default:
        target: 60%
        if_ci_failed: error
# https://docs.codecov.com/docs/ignoring-paths
ignore:
  - "config"
  - "docs"
  - "examples"
  - "hack"
  - "pkg/apis"
  - "pkg/client"
  - "test"
  - "*_test.go"
  - "fake_*.go"
