# NOTE: if serviceaccount admission plugin is enabled in a member cluster, pod
# propagation will only work properly with the BoundServiceAccountToken feature
# feature (enabled by default from v1.21 onwards)
apiVersion: core.kubeadmiral.io/v1alpha1
kind: FederatedTypeConfig
metadata:
  name: pods
spec:
  sourceType:
    kind: Pod
    pluralName: pods
    scope: Namespaced
    version: v1
  statusAggregation:
    enabled: true
  controllers:
    - - kubeadmiral.io/global-scheduler
    - - kubeadmiral.io/overridepolicy-controller
  statusCollection:
    enabled: true
    fields:
      - metadata.creationTimestamp
      - spec.nodeName
      - status
