apiVersion: core.kubeadmiral.io/v1alpha1
kind: FederatedTypeConfig
metadata:
  name: pods
spec:
  federatedType:
    group: types.kubeadmiral.io
    kind: FederatedPod
    pluralName: federatedpods
    scope: Namespaced
    version: v1alpha1
  targetType:
    kind: Pod
    pluralName: pods
    scope: Namespaced
    version: v1
  sourceType:
    kind: Pod
    pluralName: pods
    scope: Namespaced
    version: v1
  statusType:
    group: types.kubeadmiral.io
    kind: FederatedPodStatus
    pluralName: federatedpodstatuses
    scope: Namespaced
    version: v1alpha1
  controllers:
    - - kubeadmiral.io/global-scheduler
    - - kubeadmiral.io/overridepolicy-controller
    - - kubeadmiral.io/follower-controller
  statusCollection:
    fields:
      - metadata.creationTimestamp
      - spec.nodeName
      - status
