name: Build and push latest images to DockerHub

on:
  push:
    branches: ["main", "ci-test"]

permissions:
  packages: write

jobs:
  publish-images-to-dockerhub:
    name: Publish to DockerHub
    if: ${{ github.repository == 'kubewharf/kubeadmiral' }}
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish images
        env:
          REGISTRY: kubewharf
          TAG: latest
        run: make upload-images
